name: Issue Comment Triage

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    env:
      COMMAND: ${{ github.event.issue.pull_request && 'pr' || 'issue' }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: 'Remove waiting-response on comment'
        run: gh ${{ env.COMMAND }} edit ${{ github.event.issue.html_url }} --remove-label waiting-response
